[project]
name = "airport-database-design"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mysqlclient>=2.2.7", "sqlmodel>=0.0.24"]


[tool.ruff]
ignore = ["ERA001"] # Ignore commented out code
